/* SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Rithul Kamesh
 * Author: Rithul Kamesh <hi@rithul.dev>
 * Description: sdk/cpp/include/licensify.hpp — C++ SDK wrapper types around the Licensify C ABI.
 */

#pragma once

/*
Licensify C++ SDK

This is a small RAII wrapper over the Licensify C ABI (`licensify_*`) generated by the Rust client.
It validates inputs, converts native error codes into typed exceptions, and ensures native resources
are freed deterministically via `close()`/destructor.
*/

#include <cstdint>
#include <stdexcept>
#include <string>
#include <utility>

extern "C" {
#include "licensify.h"
}

namespace Licensify {

struct Logger {
  virtual ~Logger() = default;
  virtual void debug(const std::string& msg) = 0;
  virtual void info(const std::string& msg) = 0;
  virtual void warn(const std::string& msg) = 0;
  virtual void error(const std::string& msg) = 0;
};

class InitializationError : public std::runtime_error {
 public:
  using std::runtime_error::runtime_error;
};

class ActivationError : public std::runtime_error {
 public:
  explicit ActivationError(licensify_error_code_t code, const std::string& msg)
      : std::runtime_error(msg), code_(code) {}
  licensify_error_code_t code() const noexcept { return code_; }

 private:
  licensify_error_code_t code_;
};

class CheckError : public std::runtime_error {
 public:
  explicit CheckError(licensify_error_code_t code, const std::string& msg)
      : std::runtime_error(msg), code_(code) {}
  licensify_error_code_t code() const noexcept { return code_; }

 private:
  licensify_error_code_t code_;
};

struct Config {
  std::string server_url;
  std::string cache_path;
  Logger* logger = nullptr;
};

class Client {
 public:
  Client() = default;

  static Client create(const Config& cfg) {
    if (cfg.server_url.empty()) throw InitializationError("server_url is required");
    if (cfg.cache_path.empty()) throw InitializationError("cache_path is required");
    licensify_config_t c_cfg{cfg.server_url.c_str(), cfg.cache_path.c_str()};
    auto* ptr = licensify_new(&c_cfg);
    if (!ptr) throw InitializationError("native initialization failed (NULL client)");
    Client c;
    c.client_ = ptr;
    c.logger_ = cfg.logger;
    return c;
  }

  Client(const Client&) = delete;
  Client& operator=(const Client&) = delete;

  Client(Client&& other) noexcept { *this = std::move(other); }
  Client& operator=(Client&& other) noexcept {
    if (this != &other) {
      close();
      client_ = other.client_;
      logger_ = other.logger_;
      other.client_ = nullptr;
      other.logger_ = nullptr;
    }
    return *this;
  }

  ~Client() { close(); }

  void close() noexcept {
    if (client_) {
      licensify_free(client_);
      client_ = nullptr;
    }
  }

  void activate(const std::string& key) {
    requireOpen();
    if (key.empty()) throw ActivationError(LICENSIFY_ERR_INVALID_ARGUMENT, "license key is required");
    const auto code = licensify_activate_code(client_, key.c_str());
    if (code != LICENSIFY_OK) {
      const std::string msg = lastErrorOr("activation failed");
      if (logger_) logger_->error(msg);
      throw ActivationError(code, msg);
    }
    if (logger_) logger_->info("activate ok");
  }

  int check() {
    requireOpen();
    int out = 0;
    const auto code = licensify_check_code(client_, &out);
    if (code != LICENSIFY_OK) {
      const std::string msg = lastErrorOr("check failed");
      if (logger_) logger_->error(msg);
      throw CheckError(code, msg);
    }
    if (logger_) logger_->debug("check ok");
    return out;
  }

  bool hasFeature(const std::string& feature) {
    requireOpen();
    if (feature.empty()) return false;
    return licensify_has_feature(client_, feature.c_str());
  }

 private:
  void requireOpen() const {
    if (!client_) throw InitializationError("client is closed");
  }

  std::string lastErrorOr(const std::string& fallback) const {
    const char* s = licensify_last_error(client_);
    if (!s) return fallback;
    return std::string(s);
  }

  licensify_client_t* client_ = nullptr;
  Logger* logger_ = nullptr;
};

}  // namespace Licensify
